### PR TITLE
easiest installation on Debian/Ubuntu is apt

### PR DESCRIPTION
**Pull request by drew-parsons**
conda introduces additional complications which make it not the easy way to install FEniCS on a Debian or Ubuntu (apt) based system.

### CODE REVIEW

**Comment by jorgensd** [comment]
Fair point. Should we add a note on how to choose an appropriate petsc version as well ?

**Comment by drew-parsons** [comment]
I think not for this page, it should be just basic installation here.  The standard installation would install the default real number build.  Setting up for the complex number build is a higher order skill (likewise for alternative petsc versions).  Probably good to document it but not on this page, or at least not at this point ("Getting started").

Let's take a moment to think where the best location for complex number documentation would be.  Could add an extra section on this download page. But I suspect it might be better on its own page (conda would also need some discussion about its complex number build.  Perhaps docker too).

**Comment by drew-parsons** [comment]
Thinking about, there's space to address complex builds on this page. It fits logically enough after "FEniCSx vs legacy FEniCS".  I'll add a paragraph there for Debian/Ubuntu.  If you like it, then you (or @minrk) could add a corresponding comment for conda complex.

**Comment by jorgensd** [comment]
I think we should merge this for now, and add a note about conda once we have the windows-build up and running.

**Pull request merged**
